
/* const stackoverflow = [
    {name: 'HTML', selected: true}, 
    {name: 'CSS', selected: true}, 
    {name: 'JavaScript', selected: true}, 
    {name: 'Reactjs', selected: true}, 
    {name: 'SQL', selected: false}, 
    {name: 'mongo', selected: false}, 
    {name: 'PHP', selected: false}, 
    {name: 'Node.js', selected: false}, 
  ]  */

const stackoverflow = [
  { name: 'testerror', selected: true },
  { name: '.net', selected: false },
  { name: 'android', selected: false },
  { name: 'angular', selected: false },
  { name: 'arrays', selected: false },
  { name: 'asp.net', selected: false },
  { name: 'c', selected: false },
  { name: 'c#', selected: false },
  { name: 'c++', selected: false },
  { name: 'css', selected: false },
  { name: 'django', selected: false },
  { name: 'excel', selected: false },
  { name: 'html', selected: false },
  { name: 'ios', selected: false },
  { name: 'java', selected: true },
  { name: 'javascript', selected: true },
  { name: 'jquery', selected: false },
  { name: 'json', selected: false },
  { name: 'mysql', selected: false },
  { name: 'node.js', selected: false },
  { name: 'objective-c', selected: false },
  { name: 'pandas', selected: false },
  { name: 'php', selected: false },
  { name: 'python', selected: true },
  { name: 'python-3.x', selected: false },
  { name: 'r', selected: false },
  { name: 'reactjs', selected: false },
  { name: 'ruby-on-rails', selected: false },
  { name: 'sql', selected: false },
  { name: 'sql-server', selected: false },
  { name: 'swift', selected: false }
]

const superuser = [
  { name: 'audio', selected: false },
  { name: 'bash', selected: false },
  { name: 'boot', selected: false },
  { name: 'command-line', selected: false },
  { name: 'drivers', selected: false },
  { name: 'ffmpeg', selected: false },
  { name: 'firefox', selected: false },
  { name: 'google-chrome', selected: false },
  { name: 'hard-drive', selected: false },
  { name: 'laptop', selected: false },
  { name: 'linux', selected: true },
  { name: 'mac', selected: false },
  { name: 'macos', selected: false },
  { name: 'memory', selected: false },
  { name: 'microsoft-excel', selected: false },
  { name: 'microsoft-word', selected: false },
  { name: 'networking', selected: false },
  { name: 'partitioning', selected: false },
  { name: 'router', selected: false },
  { name: 'ssh', selected: false },
  { name: 'ubuntu', selected: false },
  { name: 'usb', selected: false },
  { name: 'virtualbox', selected: false },
  { name: 'windows', selected: true },
  { name: 'windows-10', selected: false },
  { name: 'windows-7', selected: true },
  { name: 'windows-8', selected: false },
  { name: 'windows-xp', selected: false },
  { name: 'wireless-networking', selected: false },
  { name: 'worksheet-function', selected: false }
]

const askubuntu = [
  { name: '12.04', selected: false },
  { name: '14.04', selected: false },
  { name: '16.04', selected: false },
  { name: '18.04', selected: false },
  { name: '20.04', selected: false },
  { name: 'apt', selected: false },
  { name: 'bash', selected: false },
  { name: 'boot', selected: true },
  { name: 'command-line', selected: true },
  { name: 'drivers', selected: false },
  { name: 'dual-boot', selected: false },
  { name: 'gnome', selected: false },
  { name: 'grub2', selected: false },
  { name: 'kernel', selected: false },
  { name: 'mount', selected: false },
  { name: 'networking', selected: true },
  { name: 'nvidia', selected: false },
  { name: 'package-management', selected: false },
  { name: 'partitioning', selected: false },
  { name: 'permissions', selected: false },
  { name: 'scripts', selected: false },
  { name: 'server', selected: false },
  { name: 'software-installation', selected: false },
  { name: 'sound', selected: false },
  { name: 'system-installation', selected: false },
  { name: 'unity', selected: false },
  { name: 'updates', selected: false },
  { name: 'upgrade', selected: false },
  { name: 'usb', selected: false },
  { name: 'wireless', selected: false }
]

const italian = [
  { name: 'adjectives', selected: false },
  { name: 'adverbs', selected: false },
  { name: 'agreement', selected: false },
  { name: 'articles', selected: false },
  { name: 'difference', selected: false },
  { name: 'english-comparison', selected: false },
  { name: 'etymology', selected: false },
  { name: 'gender', selected: false },
  { name: 'grammar', selected: false },
  { name: 'history', selected: false },
  { name: 'idioms', selected: false },
  { name: 'meaning', selected: true },
  { name: 'nouns', selected: false },
  { name: 'orthography', selected: false },
  { name: 'phrase-origin', selected: false },
  { name: 'phrase-request', selected: false },
  { name: 'prepositions', selected: false },
  { name: 'pronouns', selected: false },
  { name: 'pronunciation', selected: false },
  { name: 'regional', selected: false },
  { name: 'sentences', selected: false },
  { name: 'single-words', selected: false },
  { name: 'subjunctive-mood', selected: false },
  { name: 'tenses', selected: false },
  { name: 'translation', selected: false },
  { name: 'verbs', selected: false },
  { name: 'vocabulary', selected: false },
  { name: 'word-choice', selected: false },
  { name: 'word-meaning', selected: true },
  { name: 'word-usage', selected: true }
]

const serverfault = [
  { name: 'active-directory', selected: false },
  { name: 'amazon-ec2', selected: false },
  { name: 'amazon-web-services', selected: false },
  { name: 'apache-2.2', selected: true },
  { name: 'apache-2.4', selected: false },
  { name: 'centos', selected: false },
  { name: 'debian', selected: false },
  { name: 'docker', selected: false },
  { name: 'domain-name-system', selected: false },
  { name: 'email', selected: false },
  { name: 'firewall', selected: false },
  { name: 'iis', selected: false },
  { name: 'iptables', selected: false },
  { name: 'linux', selected: true },
  { name: 'mysql', selected: false },
  { name: 'networking', selected: false },
  { name: 'nginx', selected: false },
  { name: 'php', selected: false },
  { name: 'postfix', selected: false },
  { name: 'powershell', selected: false },
  { name: 'security', selected: false },
  { name: 'sql-server', selected: false },
  { name: 'ssh', selected: false },
  { name: 'ssl', selected: false },
  { name: 'ubuntu', selected: false },
  { name: 'vpn', selected: false },
  { name: 'windows', selected: true },
  { name: 'windows-server-2003', selected: false },
  { name: 'windows-server-2008', selected: false },
  { name: 'windows-server-2008-r2', selected: false }
]

const cooking = [
  { name: 'baking', selected: true },
  { name: 'beef', selected: false },
  { name: 'bread', selected: false },
  { name: 'cake', selected: false },
  { name: 'cheese', selected: false },
  { name: 'chicken', selected: false },
  { name: 'chocolate', selected: false },
  { name: 'cleaning', selected: false },
  { name: 'cookies', selected: false },
  { name: 'dough', selected: false },
  { name: 'eggs', selected: false },
  { name: 'equipment', selected: false },
  { name: 'fish', selected: false },
  { name: 'flavor', selected: false },
  { name: 'food-preservation', selected: false },
  { name: 'food-safety', selected: true },
  { name: 'food-science', selected: false },
  { name: 'freezing', selected: false },
  { name: 'frying', selected: false },
  { name: 'meat', selected: false },
  { name: 'oil', selected: false },
  { name: 'oven', selected: false },
  { name: 'pasta', selected: false },
  { name: 'sauce', selected: false },
  { name: 'storage-lifetime', selected: false },
  { name: 'storage-method', selected: false },
  { name: 'substitutions', selected: true },
  { name: 'sugar', selected: false },
  { name: 'temperature', selected: false },
  { name: 'vegetables', selected: false }
]
const math = [
  { name: 'abstract-algebra', selected: false },
  { name: 'algebra-precalculus', selected: false },
  { name: 'analysis', selected: false },
  { name: 'calculus', selected: true },
  { name: 'combinatorics', selected: false },
  { name: 'complex-analysis', selected: false },
  { name: 'derivatives', selected: false },
  { name: 'differential-geometry', selected: false },
  { name: 'discrete-mathematics', selected: false },
  { name: 'elementary-number-theory', selected: false },
  { name: 'functional-analysis', selected: false },
  { name: 'functions', selected: false },
  { name: 'general-topology', selected: false },
  { name: 'geometry', selected: false },
  { name: 'group-theory', selected: false },
  { name: 'inequality', selected: false },
  { name: 'integration', selected: false },
  { name: 'limits', selected: false },
  { name: 'linear-algebra', selected: true },
  { name: 'matrices', selected: false },
  { name: 'measure-theory', selected: false },
  { name: 'multivariable-calculus', selected: false },
  { name: 'number-theory', selected: false },
  { name: 'ordinary-differential-equations', selected: false },
  { name: 'probability', selected: false },
  { name: 'probability-theory', selected: false },
  { name: 'real-analysis', selected: true },
  { name: 'sequences-and-series', selected: false },
  { name: 'statistics', selected: false },
  { name: 'trigonometry', selected: false }
]

const english = [
  { name: 'adjectives', selected: false },
  { name: 'american-english', selected: false },
  { name: 'british-english', selected: false },
  { name: 'commas', selected: false },
  { name: 'differences', selected: false },
  { name: 'etymology', selected: false },
  { name: 'expressions', selected: false },
  { name: 'grammar', selected: true },
  { name: 'grammatical-number', selected: false },
  { name: 'grammaticality', selected: false },
  { name: 'idioms', selected: false },
  { name: 'meaning', selected: true },
  { name: 'meaning-in-context', selected: false },
  { name: 'nouns', selected: false },
  { name: 'phrase-requests', selected: false },
  { name: 'phrases', selected: false },
  { name: 'prepositions', selected: false },
  { name: 'pronunciation', selected: false },
  { name: 'punctuation', selected: false },
  { name: 'sentence', selected: false },
  { name: 'single-word-requests', selected: true },
  { name: 'synonyms', selected: false },
  { name: 'syntactic-analysis', selected: false },
  { name: 'tenses', selected: false },
  { name: 'terminology', selected: false },
  { name: 'usage', selected: false },
  { name: 'verbs', selected: false },
  { name: 'vocabulary', selected: false },
  { name: 'word-choice', selected: false },
  { name: 'word-usage', selected: false }
]

const scifi = [
  { name: 'a-song-of-ice-and-fire', selected: false },
  { name: 'aliens', selected: false },
  { name: 'anime', selected: false },
  { name: 'books', selected: false },
  { name: 'comics', selected: false },
  { name: 'dc', selected: false },
  { name: 'doctor-who', selected: false },
  { name: 'game-of-thrones', selected: false },
  { name: 'harry-potter', selected: true },
  { name: 'history-of', selected: false },
  { name: 'horror', selected: false },
  { name: 'magic', selected: false },
  { name: 'manga', selected: false },
  { name: 'marvel', selected: false },
  { name: 'marvel-cinematic-universe', selected: false },
  { name: 'movie', selected: false },
  { name: 'novel', selected: false },
  { name: 'short-stories', selected: false },
  { name: 'star-trek', selected: false },
  { name: 'star-trek-ds9', selected: false },
  { name: 'star-trek-tng', selected: false },
  { name: 'star-wars', selected: true },
  { name: 'star-wars-legends', selected: false },
  { name: 'story-identification', selected: true },
  { name: 'the-force-awakens', selected: false },
  { name: 'the-lord-of-the-rings', selected: false },
  { name: 'time-travel', selected: false },
  { name: 'tolkiens-legendarium', selected: false },
  { name: 'tv', selected: false },
  { name: 'young-adult', selected: false }
]

const travel = [
  { name: 'air-travel', selected: false },
  { name: 'airports', selected: false },
  { name: 'bookings', selected: false },
  { name: 'canada', selected: false },
  { name: 'covid-19', selected: false },
  { name: 'customs-and-immigration', selected: false },
  { name: 'europe', selected: false },
  { name: 'france', selected: false },
  { name: 'germany', selected: false },
  { name: 'india', selected: false },
  { name: 'indian-citizens', selected: false },
  { name: 'international-travel', selected: false },
  { name: 'japan', selected: false },
  { name: 'legal', selected: false },
  { name: 'luggage', selected: false },
  { name: 'paperwork', selected: false },
  { name: 'passports', selected: false },
  { name: 'public-transport', selected: false },
  { name: 'schengen', selected: false },
  { name: 'schengen-visas', selected: false },
  { name: 'standard-visitor-visas', selected: false },
  { name: 'tickets', selected: false },
  { name: 'trains', selected: false },
  { name: 'transit', selected: false },
  { name: 'transit-visas', selected: false },
  { name: 'uk', selected: true },
  { name: 'us-citizens', selected: false },
  { name: 'usa', selected: true },
  { name: 'visa-refusals', selected: false },
  { name: 'visas', selected: true }
]

export default {stackoverflow, superuser, askubuntu, italian, serverfault, cooking, math, english, scifi, travel}