const sites = [
  { value: 'gaming', name: 'Arqade' },
  { value: 'askubuntu', name: 'Ask Ubuntu' },
  { value: 'astronomy', name: 'Astronomy' },
  { value: 'bicycles', name: 'Bicycles' },
  { value: 'bioacoustics', name: 'Bioacoustics' },
  { value: 'chemistry', name: 'Chemistry' },
  { value: 'dba', name: 'Database Administrators' },
  { value: 'devops', name: 'DevOps' },
  { value: 'english', name: 'English Language & Usage' },
  { value: 'history', name: 'History' },
  { value: 'homebrew', name: 'Homebrewing' },
  { value: 'italian', name: 'Italian Language' },
  { value: 'languagelearning', name: 'Language Learning' },
  { value: 'linguistics', name: 'Linguistics' },
  { value: 'literature', name: 'Literature' },
  { value: 'math', name: 'Mathematics' },
  { value: 'photo', name: 'Photography' },
  { value: 'salesforce', name: 'Salesforce' },
  { value: 'scifi', name: 'Science Fiction & Fantasy' },
  { value: 'cooking', name: 'Seasoned Advice' },
  { value: 'serverfault', name: 'Server Fault' },
  { value: 'softwarerecs', name: 'Software Recommendations' },
  { value: 'solana', name: 'Solana' },
  { value: 'sound', name: 'Sound Design' },
  { value: 'spanish', name: 'Spanish Language' },
  { value: 'stackoverflow', name: 'Stack Overflow' },
  { value: 'superuser', name: 'Superuser' },
  { value: 'cstheory', name: 'Theoretical Computer Science' },
  { value: 'travel', name: 'Travel' },
  { value: 'unix', name: 'Unix & Linux' },
  { value: 'ux', name: 'User Experience' },
  { value: 'worldbuilding', name: 'Worldbuilding' }
]

export default {sites}